# GFlowNet Training Configuration for Melody Agent

# Melody model configuration (fine-tuned model)
melody_model:
  model_name: "microsoft/DialoGPT-medium"  # Replace with your base model
  device: "cuda"
  quantization: "4bit"
  batch_size: 1
  max_length: 2048
  temperature: 0.7
  top_p: 0.9
  top_k: 50

# API model configuration (for other agents)
api_model:
  model_name: "meta-llama/Llama-2-7b-chat-hf"  # Replace with your API model
  base_url: "https://api.deepinfra.com/v1/openai"
  api_key: "${DEEPINFRA_API_KEY}"  # Will be substituted from environment variable
  batch_size: 1
  max_length: 2048
  temperature: 0.7
  top_p: 0.9
  top_k: 50

# Output directory
output_dir: "output" 