melody_model:
  model_name: meta-llama/Meta-Llama-3.1-8B-Instruct
  device: cuda
  quantization: 4bit
  batch_size: 1
  max_length: 2048
  temperature: 0.7
  top_p: 0.9
  top_k: 50

api_model:
  model_name: meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8
  base_url: https://api.deepinfra.com/v1/openai
  api_key: ${DEEPINFRA_API_KEY}
  batch_size: 1
  max_length: 2048
  temperature: 0.7
  top_p: 0.9
  top_k: 50

output_dir: output
